### PR TITLE
Sync json file with Coinmarketcap.com

### PR DESCRIPTION
**Pull request by jvandenaardweg**
Hi there! First of all; thanks for the list! :-)

Secondly: I noticed some coins were missing when I used it in a project of mine. So I created a sync method in my own project. Thought it might be helpful here.

`sync.js` takes gets all the currencies from [coinmarketcap.com](https://coinmarketcap.com) and finds out what is missing in `cryptocurrencies.json`. In the end it merges the missing symbols resulting in a new up-to-date list. So, if something is not listed on coinmarketcap, you still have the ability to add it directly to `cryptocurrencies.json`

1. Install new dependencies: `npm install`
2. Run sync: `npm run sync`
3. If there are new currencies, `cryptocurrencies.json` is updated and sorted correctly.

### CODE REVIEW

**Comment by radiovisual** [comment]
Ooooo! This is a nice idea! Thanks!

Can you update the Readme in this PR to let reader's know that we also pull from coinmarketcap? I like this idea, because it helps the list be more complete. 

I will take a closer look at this tomorrow.

Thanks again, this is really cool.

**Comment by jvandenaardweg** [comment]
No problem!

Updated the readme 👍

**Comment by pml10628** [comment]
Realbank(RBT)-1ede817398a84d4c8533f423444681cf

**Comment by pml10628** [comment]
coin-in system481

Icon

**Pull request closed without merging**
